WORDS = [
    {"kr": "나라", "roman": "nara", "uz": "davlat", "tts": "나라", "example_kr": "", "example_uz": ""},
    {"kr": "중국", "roman": "jungguk", "uz": "Xitoy", "tts": "중국", "example_kr": "", "example_uz": ""},
    {"kr": "일본", "roman": "ilbon", "uz": "Yaponiya", "tts": "일본", "example_kr": "", "example_uz": ""},
    {"kr": "미국", "roman": "miguk", "uz": "AQSH", "tts": "미국", "example_kr": "", "example_uz": ""},
    {"kr": "한국", "roman": "hanguk", "uz": "Koreya", "tts": "한국", "example_kr": "", "example_uz": ""},
    {"kr": "프랑스", "roman": "peurangseu", "uz": "Fransiya", "tts": "프랑스", "example_kr": "", "example_uz": ""},
    {"kr": "독일", "roman": "dogil", "uz": "Germaniya", "tts": "독일", "example_kr": "", "example_uz": ""},
    {"kr": "호주", "roman": "hoju", "uz": "Avstraliya", "tts": "호주", "example_kr": "", "example_uz": ""},
    {"kr": "영국", "roman": "yeongguk", "uz": "Angliya", "tts": "영국", "example_kr": "", "example_uz": ""},
    {"kr": "빈칸", "roman": "binkan", "uz": "bo'sh joy", "tts": "빈칸", "example_kr": "", "example_uz": ""},
    {"kr": "알맞다", "roman": "almajt-ta", "uz": "mos", "tts": "알맞다", "example_kr": "", "example_uz": ""},
    {"kr": "단어", "roman": "daneo", "uz": "so'z", "tts": "단어", "example_kr": "", "example_uz": ""},
    {"kr": "선생님", "roman": "seonsaengnim", "uz": "o'qituvchi", "tts": "선생님", "example_kr": "", "example_uz": ""},
    {"kr": "학생", "roman": "haksaeng", "uz": "o'quvchi", "tts": "학생", "example_kr": "", "example_uz": ""},
    {"kr": "의사", "roman": "uisa", "uz": "doktor", "tts": "의사", "example_kr": "", "example_uz": ""},
    {"kr": "회사원", "roman": "hoesawon", "uz": "firma ishchisi", "tts": "회사원", "example_kr": "", "example_uz": ""},
    {"kr": "요리사", "roman": "yorisa", "uz": "oshpaz", "tts": "요리사", "example_kr": "", "example_uz": ""},
    {"kr": "기자", "roman": "gija", "uz": "muxbir", "tts": "기자", "example_kr": "", "example_uz": ""},
    {"kr": "가수", "roman": "gasu", "uz": "qo'shiqchi", "tts": "가수", "example_kr": "", "example_uz": ""},
    {"kr": "군인", "roman": "gunin", "uz": "askar", "tts": "군인", "example_kr": "", "example_uz": ""},
    {"kr": "인사말", "roman": "insammal", "uz": "salomlashish gapi", "tts": "인사말", "example_kr": "", "example_uz": ""},
    {"kr": "만나다", "roman": "mannada", "uz": "uchrashmoq", "tts": "만나다", "example_kr": "", "example_uz": ""},
    {"kr": "반갑다", "roman": "bangaptta", "uz": "xursand bo‘lmoq", "tts": "반갑다", "example_kr": "", "example_uz": ""},
    {"kr": "한국말", "roman": "hangungmal", "uz": "koreys tili", "tts": "한국말", "example_kr": "", "example_uz": ""},
    {"kr": "그림", "roman": "geurim", "uz": "surat", "tts": "그림", "example_kr": "", "example_uz": ""},
    {"kr": "이야기하다", "roman": "iyagi-hada", "uz": "suhbatlashmoq", "tts": "이야기하다", "example_kr": "", "example_uz": ""},
    {"kr": "저", "roman": "jeo", "uz": "men", "tts": "저", "example_kr": "", "example_uz": ""},
    {"kr": "씨", "roman": "ssi", "uz": "janob/xonim", "tts": "씨", "example_kr": "", "example_uz": ""},
    {"kr": "네", "roman": "ne", "uz": "ha", "tts": "네", "example_kr": "", "example_uz": ""},
    {"kr": "주부", "roman": "jubu", "uz": "uy bekasi", "tts": "주부", "example_kr": "", "example_uz": ""},
    {"kr": "말하기", "roman": "malhagi", "uz": "gaplashish", "tts": "말하기", "example_kr": "", "example_uz": ""},
    {"kr": "어느", "roman": "eoneu", "uz": "qaysi", "tts": "어느", "example_kr": "", "example_uz": ""},
    {"kr": "캐나다", "roman": "kaenada", "uz": "Kanada", "tts": "캐나다", "example_kr": "", "example_uz": ""},
    {"kr": "국적", "roman": "gukjeok", "uz": "millat", "tts": "국적", "example_kr": "", "example_uz": ""},
    {"kr": "묻다", "roman": "mutta", "uz": "so‘ramoq", "tts": "묻다", "example_kr": "", "example_uz": ""},
    {"kr": "인도", "roman": "indo", "uz": "Hindiston", "tts": "인도", "example_kr": "", "example_uz": ""},
    {"kr": "직업", "roman": "jigeop", "uz": "kasb", "tts": "직업", "example_kr": "", "example_uz": ""},
    {"kr": "아니요", "roman": "aniyo", "uz": "yo‘q", "tts": "아니요", "example_kr": "", "example_uz": ""},
    {"kr": "여러분", "roman": "yeoreobun", "uz": "sizlar", "tts": "여러분", "example_kr": "", "example_uz": ""},
    {"kr": "무엇", "roman": "mueot", "uz": "nima", "tts": "무엇", "example_kr": "", "example_uz": ""},
    {"kr": "러시아", "roman": "reosia", "uz": "Rossiya", "tts": "러시아", "example_kr": "", "example_uz": ""},
    {"kr": "파키스탄", "roman": "pakiseutan", "uz": "Pokiston", "tts": "파키스탄", "example_kr": "", "example_uz": ""},
    {"kr": "친구", "roman": "chingu", "uz": "do‘st", "tts": "친구", "example_kr": "", "example_uz": ""},
    {"kr": "명함", "roman": "myeongham", "uz": "ism karta", "tts": "명함", "example_kr": "", "example_uz": ""},
    {"kr": "이름", "roman": "ireum", "uz": "ism", "tts": "이름", "example_kr": "", "example_uz": ""},
    {"kr": "전화번호", "roman": "jeonhwabeonho", "uz": "telefon raqam", "tts": "전화번호", "example_kr": "", "example_uz": ""},
    {"kr": "영어", "roman": "yeongeo", "uz": "ingliz tili", "tts": "영어", "example_kr": "", "example_uz": ""},
    {"kr": "블로그", "roman": "beullogeu", "uz": "blog", "tts": "블로그", "example_kr": "", "example_uz": ""},
    {"kr": "찾다", "roman": "chatda", "uz": "qidirmoq", "tts": "찾다", "example_kr": "", "example_uz": ""},
    {"kr": "과제", "roman": "gwaje", "uz": "topshiriq", "tts": "과제", "example_kr": "", "example_uz": ""},
    {"kr": "문화", "roman": "munhwa", "uz": "madaniyat", "tts": "문화", "example_kr": "", "example_uz": ""}
]
