WORDS = [
    {"kr": "책상", "roman": "chaeksang", "uz": "parta", "tts": "책상", "example_kr": "", "example_uz": ""},
    {"kr": "의자", "roman": "uija", "uz": "stul", "tts": "의자", "example_kr": "", "example_uz": ""},
    {"kr": "책", "roman": "chaek", "uz": "kitob", "tts": "책", "example_kr": "", "example_uz": ""},
    {"kr": "공책", "roman": "gongchaek", "uz": "daftar", "tts": "공책", "example_kr": "", "example_uz": ""},
    {"kr": "볼펜", "roman": "bolpen", "uz": "ruchka", "tts": "볼펜", "example_kr": "", "example_uz": ""},
    {"kr": "연필", "roman": "yeonpil", "uz": "qalam", "tts": "연필", "example_kr": "", "example_uz": ""},
    {"kr": "가방", "roman": "gabang", "uz": "sumka", "tts": "가방", "example_kr": "", "example_uz": ""},
    {"kr": "지우개", "roman": "jiugae", "uz": "o‘chirgi‘ch", "tts": "지우개", "example_kr": "", "example_uz": ""},
    {"kr": "시계", "roman": "sigye", "uz": "soat", "tts": "시계", "example_kr": "", "example_uz": ""},
    {"kr": "모자", "roman": "moja", "uz": "bosh kiyim", "tts": "모자", "example_kr": "", "example_uz": ""},
    {"kr": "우산", "roman": "usan", "uz": "soyabon", "tts": "우산", "example_kr": "", "example_uz": ""},
    {"kr": "신문", "roman": "sinmun", "uz": "gazeta", "tts": "신문", "example_kr": "", "example_uz": ""},
    {"kr": "사전", "roman": "sajeon", "uz": "lug‘at", "tts": "사전", "example_kr": "", "example_uz": ""},
    {"kr": "안경", "roman": "angyeong", "uz": "ko‘zoynak", "tts": "안경", "example_kr": "", "example_uz": ""},
    {"kr": "휴대폰", "roman": "hyudaepon", "uz": "telefon", "tts": "휴대폰", "example_kr": "", "example_uz": ""},
    {"kr": "남자친구", "roman": "namja chingu", "uz": "yigit o‘rtoq", "tts": "남자친구", "example_kr": "", "example_uz": ""},
    {"kr": "동전", "roman": "dongjeon", "uz": "tanga", "tts": "동전", "example_kr": "", "example_uz": ""},
    {"kr": "차", "roman": "cha", "uz": "mashina", "tts": "차", "example_kr": "", "example_uz": ""},
    {"kr": "한국어", "roman": "hangug-eo", "uz": "koreys tili", "tts": "한국어", "example_kr": "", "example_uz": ""},
    {"kr": "여자 친구", "roman": "yeoja chingu", "uz": "qiz o‘rtoq", "tts": "여자 친구", "example_kr": "", "example_uz": ""},
    {"kr": "뭐", "roman": "mwo", "uz": "nima", "tts": "뭐", "example_kr": "", "example_uz": ""},
    {"kr": "창문", "roman": "changmun", "uz": "deraza", "tts": "창문", "example_kr": "", "example_uz": ""},
    {"kr": "지도", "roman": "jido", "uz": "xarita", "tts": "지도", "example_kr": "", "example_uz": ""},
    {"kr": "필통", "roman": "piltong", "uz": "penal/qalamdon", "tts": "필통", "example_kr": "", "example_uz": ""},
    {"kr": "전자사전", "roman": "jeonja sajeon", "uz": "elektron lug‘at", "tts": "전자사전", "example_kr": "", "example_uz": ""},
    {"kr": "한국어로", "roman": "hangug-eoro", "uz": "koreys tilida", "tts": "한국어로", "example_kr": "", "example_uz": ""},
    {"kr": "자", "roman": "ja", "uz": "chizg‘ich", "tts": "자", "example_kr": "", "example_uz": ""},
    {"kr": "잡지", "roman": "japji", "uz": "jurnal", "tts": "잡지", "example_kr": "", "example_uz": ""},
    {"kr": "지갑", "roman": "jigap", "uz": "hamyon", "tts": "지갑", "example_kr": "", "example_uz": ""},
    {"kr": "여기 있어요", "roman": "yeogi iss-eoyo", "uz": "marhamat", "tts": "여기 있어요", "example_kr": "", "example_uz": ""},
    {"kr": "커피", "roman": "keopi", "uz": "kofe", "tts": "커피", "example_kr": "", "example_uz": ""},
    {"kr": "좀", "roman": "jom", "uz": "iltimos", "tts": "좀", "example_kr": "", "example_uz": ""},
    {"kr": "콜라", "roman": "kolla", "uz": "kola", "tts": "콜라", "example_kr": "", "example_uz": ""},
    {"kr": "주스", "roman": "juseu", "uz": "sharbat", "tts": "주스", "example_kr": "", "example_uz": ""},
    {"kr": "교통카드", "roman": "gyotong kadeu", "uz": "transport kartasi", "tts": "교통카드", "example_kr": "", "example_uz": ""},
    {"kr": "휴지", "roman": "hyuji", "uz": "salfetka", "tts": "휴지", "example_kr": "", "example_uz": ""},
    {"kr": "물", "roman": "mul", "uz": "suv", "tts": "물", "example_kr": "", "example_uz": ""},
    {"kr": "어서 오세요", "roman": "eoseo oseyo", "uz": "xush kelibsiz", "tts": "어서 오세요", "example_kr": "", "example_uz": ""},
    {"kr": "사과", "roman": "sagwa", "uz": "olma", "tts": "사과", "example_kr": "", "example_uz": ""},
    {"kr": "오랜지", "roman": "orenji", "uz": "apelsin", "tts": "오랜지", "example_kr": "", "example_uz": ""},
    {"kr": "영화", "roman": "yeonghwa", "uz": "kino", "tts": "영화", "example_kr": "", "example_uz": ""},
    {"kr": "우유", "roman": "uyu", "uz": "sut", "tts": "우유", "example_kr": "", "example_uz": ""},
    {"kr": "바나나", "roman": "banana", "uz": "banan", "tts": "바나나", "example_kr": "", "example_uz": ""},
    {"kr": "딸기", "roman": "ttalgi", "uz": "qulupnay", "tts": "딸기", "example_kr": "", "example_uz": ""},
    {"kr": "텔레비전", "roman": "tellebijeon", "uz": "televizor", "tts": "텔레비전", "example_kr": "", "example_uz": ""},
    {"kr": "방", "roman": "bang", "uz": "xona", "tts": "방", "example_kr": "", "example_uz": ""},
    {"kr": "서울대학교", "roman": "seouldaehaggyo", "uz": "Seul universiteti", "tts": "서울대학교", "example_kr": "", "example_uz": ""},
    {"kr": "제", "roman": "je", "uz": "mening", "tts": "제", "example_kr": "", "example_uz": ""},
    {"kr": "침대", "roman": "chimdae", "uz": "kravat", "tts": "침대", "example_kr": "", "example_uz": ""},
    {"kr": "룸메이트", "roman": "rummeiteu", "uz": "xonadosh", "tts": "룸메이트", "example_kr": "", "example_uz": ""},
    {"kr": "에어컨", "roman": "eeokeon", "uz": "konditsioner", "tts": "에어컨", "example_kr": "", "example_uz": ""},
    {"kr": "물건", "roman": "mulgeon", "uz": "narsa", "tts": "물건", "example_kr": "", "example_uz": ""},
    {"kr": "팀", "roman": "tim", "uz": "jamoa", "tts": "팀", "example_kr": "", "example_uz": ""},
    {"kr": "나누다", "roman": "nanuda", "uz": "bo‘lishmoq", "tts": "나누다", "example_kr": "", "example_uz": ""},
    {"kr": "받다", "roman": "batda", "uz": "olmoq", "tts": "받다", "example_kr": "", "example_uz": ""},
    {"kr": "붙이다", "roman": "buchida", "uz": "yopishtirmoq", "tts": "붙이다", "example_kr": "", "example_uz": ""}
]
