WORDS = [
    {"kr": "자다", "roman": "jada", "uz": "uxlamoq", "tts": "자다", "example_kr": "", "example_uz": ""},
    {"kr": "공부하다", "roman": "gongbu-hada", "uz": "o‘qimoq / o‘rganmoq", "tts": "공부하다", "example_kr": "", "example_uz": ""},
    {"kr": "일하다", "roman": "ilhada", "uz": "ishlamoq", "tts": "일하다", "example_kr": "", "example_uz": ""},
    {"kr": "운동하다", "roman": "undong-hada", "uz": "sport bilan shug‘ullanmoq", "tts": "운동하다", "example_kr": "", "example_uz": ""},
    {"kr": "숙제를 하다", "roman": "sukjereul hada", "uz": "uy vazifa qilmoq", "tts": "숙제를 하다", "example_kr": "", "example_uz": ""},
    {"kr": "옷을 사다", "roman": "oseul sada", "uz": "kiyim sotib olmoq", "tts": "옷을 사다", "example_kr": "", "example_uz": ""},
    {"kr": "영화를 보다", "roman": "yeonghwareul boda", "uz": "kino ko‘rmoq", "tts": "영화를 보다", "example_kr": "", "example_uz": ""},
    {"kr": "친구를 만나다", "roman": "chingureul mannada", "uz": "do‘sti bilan uchrashmoq", "tts": "친구를 만나다", "example_kr": "", "example_uz": ""},
    {"kr": "태권도를 배우다", "roman": "taeggwondo-reul baeuda", "uz": "taekwondo o‘rganmoq", "tts": "태권도를 배우다", "example_kr": "", "example_uz": ""},
    {"kr": "밥을 먹다", "roman": "babeul meokda", "uz": "ovqat yemoq", "tts": "밥을 먹다", "example_kr": "", "example_uz": ""},
    {"kr": "커피를 마시다", "roman": "keopireul masida", "uz": "kofe ichmoq", "tts": "커피를 마시다", "example_kr": "", "example_uz": ""},
    {"kr": "책을 읽다", "roman": "chaegeul ikda", "uz": "kitob o‘qimoq", "tts": "책을 읽다", "example_kr": "", "example_uz": ""},
    {"kr": "도서관", "roman": "doseogwan", "uz": "kutubxona", "tts": "도서관", "example_kr": "", "example_uz": ""},
    {"kr": "집", "roman": "jip", "uz": "uy", "tts": "집", "example_kr": "", "example_uz": ""},
    {"kr": "백화점", "roman": "baekhwajeom", "uz": "univermag", "tts": "백화점", "example_kr": "", "example_uz": ""},
    {"kr": "시장", "roman": "sijang", "uz": "bozor", "tts": "시장", "example_kr": "", "example_uz": ""},
    {"kr": "공원", "roman": "gongwon", "uz": "bog‘ / park", "tts": "공원", "example_kr": "", "example_uz": ""},
    {"kr": "커피숍", "roman": "keopisyop", "uz": "kafe", "tts": "커피숍", "example_kr": "", "example_uz": ""},
    {"kr": "극장", "roman": "geukjang", "uz": "kinoteatr", "tts": "극장", "example_kr": "", "example_uz": ""},
    {"kr": "학교", "roman": "hakgyo", "uz": "maktab", "tts": "학교", "example_kr": "", "example_uz": ""},
    {"kr": "식당", "roman": "sikdang", "uz": "oshxona", "tts": "식당", "example_kr": "", "example_uz": ""},
    {"kr": "회사", "roman": "hoesa", "uz": "firma", "tts": "회사", "example_kr": "", "example_uz": ""},
    {"kr": "지금", "roman": "jigeum", "uz": "hozir", "tts": "지금", "example_kr": "", "example_uz": ""},
    {"kr": "하다", "roman": "hada", "uz": "qilmoq", "tts": "하다", "example_kr": "", "example_uz": ""},
    {"kr": "쉬다", "roman": "swida", "uz": "dam olmoq", "tts": "쉬다", "example_kr": "", "example_uz": ""},
    {"kr": "피자", "roman": "pija", "uz": "pitsa", "tts": "피자", "example_kr": "", "example_uz": ""},
    {"kr": "보다", "roman": "boda", "uz": "ko‘rmoq", "tts": "보다", "example_kr": "", "example_uz": ""},
    {"kr": "사다", "roman": "sada", "uz": "sotib olmoq", "tts": "사다", "example_kr": "", "example_uz": ""},
    {"kr": "먹다", "roman": "meokda", "uz": "yemoq", "tts": "먹다", "example_kr": "", "example_uz": ""},
    {"kr": "마시다", "roman": "masida", "uz": "ichmoq", "tts": "마시다", "example_kr": "", "example_uz": ""},
    {"kr": "읽다", "roman": "ikda", "uz": "o‘qimoq", "tts": "읽다", "example_kr": "", "example_uz": ""},
    {"kr": "배우다", "roman": "baeuda", "uz": "o‘rganmoq", "tts": "배우다", "example_kr": "", "example_uz": ""},
    {"kr": "일본어", "roman": "ilboneo", "uz": "yapon tili", "tts": "일본어", "example_kr": "", "example_uz": ""},
    {"kr": "아르바이트하다", "roman": "areubaiteu-hada", "uz": "qo‘shimcha ish qilmoq", "tts": "아르바이트하다", "example_kr": "", "example_uz": ""},
    {"kr": "요리", "roman": "yori", "uz": "pishirish", "tts": "요리", "example_kr": "", "example_uz": ""},
    {"kr": "만나다", "roman": "mannada", "uz": "uchrashmoq", "tts": "만나다", "example_kr": "", "example_uz": ""},
    {"kr": "오늘", "roman": "oneul", "uz": "bugun", "tts": "오늘", "example_kr": "", "example_uz": ""},
    {"kr": "그리고", "roman": "geurigo", "uz": "va", "tts": "그리고", "example_kr": "", "example_uz": ""},
    {"kr": "어디", "roman": "eodi", "uz": "qayer", "tts": "어디", "example_kr": "", "example_uz": ""},
    {"kr": "고기", "roman": "gogi", "uz": "go‘sht", "tts": "고기", "example_kr": "", "example_uz": ""},
    {"kr": "프랑스어", "roman": "peurangseueo", "uz": "fransuz tili", "tts": "프랑스어", "example_kr": "", "example_uz": ""},
    {"kr": "드라마", "roman": "deurama", "uz": "serial / dorama", "tts": "드라마", "example_kr": "", "example_uz": ""},
    {"kr": "그럼", "roman": "geureom", "uz": "unday bo‘lsa", "tts": "그럼", "example_kr": "", "example_uz": ""},
    {"kr": "스포츠 센터", "roman": "seupocheu senteo", "uz": "sport markazi", "tts": "스포츠 센터", "example_kr": "", "example_uz": ""},
    {"kr": "차", "roman": "cha", "uz": "choy", "tts": "차", "example_kr": "", "example_uz": ""},
    {"kr": "가르치다", "roman": "gareuchida", "uz": "o‘qitmoq", "tts": "가르치다", "example_kr": "", "example_uz": ""},
    {"kr": "언어교육원", "roman": "eoneo gyoyugwon", "uz": "til markazi", "tts": "언어교육원", "example_kr": "", "example_uz": ""},
    {"kr": "불고기", "roman": "bulgogi", "uz": "pulgogi", "tts": "불고기", "example_kr": "", "example_uz": ""},
    {"kr": "노래방", "roman": "noraebang", "uz": "karaoke", "tts": "노래방", "example_kr": "", "example_uz": ""}
]
