WORDS = [
    {"kr": "공항", "roman": "gonghang", "uz": "aeroport", "tts": "공항", "example_kr": "", "example_uz": ""},
    {"kr": "우체국", "roman": "ucheguk", "uz": "pochta", "tts": "우체국", "example_kr": "", "example_uz": ""},
    {"kr": "대사관", "roman": "daesagwan", "uz": "elchixona", "tts": "대사관", "example_kr": "", "example_uz": ""},
    {"kr": "은행", "roman": "eunhaeng", "uz": "bank", "tts": "은행", "example_kr": "", "example_uz": ""},
    {"kr": "가게", "roman": "gage", "uz": "magazin", "tts": "가게", "example_kr": "", "example_uz": ""},
    {"kr": "약국", "roman": "yakkuk", "uz": "apteka", "tts": "약국", "example_kr": "", "example_uz": ""},
    {"kr": "병원", "roman": "byeongwon", "uz": "kasalxona", "tts": "병원", "example_kr": "", "example_uz": ""},
    {"kr": "미용실", "roman": "miyongsil", "uz": "sartaroshxona", "tts": "미용실", "example_kr": "", "example_uz": ""},
    {"kr": "위", "roman": "wi", "uz": "usti", "tts": "위", "example_kr": "", "example_uz": ""},
    {"kr": "아래", "roman": "arae", "uz": "osti", "tts": "아래", "example_kr": "", "example_uz": ""},
    {"kr": "밑", "roman": "mit", "uz": "tagi", "tts": "밑", "example_kr": "", "example_uz": ""},
    {"kr": "옆", "roman": "yeop", "uz": "yoni", "tts": "옆", "example_kr": "", "example_uz": ""},
    {"kr": "뒤", "roman": "dwi", "uz": "orqasi", "tts": "뒤", "example_kr": "", "example_uz": ""},
    {"kr": "안", "roman": "an", "uz": "ichi", "tts": "안", "example_kr": "", "example_uz": ""},
    {"kr": "앞", "roman": "ap", "uz": "oldi", "tts": "앞", "example_kr": "", "example_uz": ""},
    {"kr": "서울타워", "roman": "seoul tawoeo", "uz": "Seul minorasi", "tts": "서울타워", "example_kr": "", "example_uz": ""},
    {"kr": "명동", "roman": "myeongdong", "uz": "Myongdong", "tts": "명동", "example_kr": "", "example_uz": ""},
    {"kr": "청계천", "roman": "cheonggyecheon", "uz": "Chonkechon", "tts": "청계천", "example_kr": "", "example_uz": ""},
    {"kr": "대학로", "roman": "daehangno", "uz": "attraksionlar joyi", "tts": "대학로", "example_kr": "", "example_uz": ""},
    {"kr": "남산", "roman": "namsan", "uz": "Nam tog‘i", "tts": "남산", "example_kr": "", "example_uz": ""},
    {"kr": "인사동", "roman": "insadong", "uz": "Insadong", "tts": "인사동", "example_kr": "", "example_uz": ""},
    {"kr": "교실", "roman": "gyosil", "uz": "sinf xona", "tts": "교실", "example_kr": "", "example_uz": ""},
    {"kr": "찻집", "roman": "chatjip", "uz": "choyxona", "tts": "찻집", "example_kr": "", "example_uz": ""},
    {"kr": "서울", "roman": "seoul", "uz": "Seul", "tts": "서울", "example_kr": "", "example_uz": ""},
    {"kr": "시내", "roman": "sinae", "uz": "shahar markazi", "tts": "시내", "example_kr": "", "example_uz": ""},
    {"kr": "구경하다", "roman": "gugyeonghada", "uz": "tomo sha qilmoq", "tts": "구경하다", "example_kr": "", "example_uz": ""},
    {"kr": "쇼핑하다", "roman": "syopinghada", "uz": "xarid qilmoq", "tts": "쇼핑하다", "example_kr": "", "example_uz": ""},
    {"kr": "연극", "roman": "yeongeuk", "uz": "teatr", "tts": "연극", "example_kr": "", "example_uz": ""},
    {"kr": "알다", "roman": "alda", "uz": "bilmoq", "tts": "알다", "example_kr": "", "example_uz": ""},
    {"kr": "어머니", "roman": "eomeoni", "uz": "ona", "tts": "어머니", "example_kr": "", "example_uz": ""},
    {"kr": "아버지", "roman": "abeoji", "uz": "ota", "tts": "아버지", "example_kr": "", "example_uz": ""},
    {"kr": "잘 지내다", "roman": "jal jinaeda", "uz": "ishlari yaxshi bo‘lmoq", "tts": "잘 지내다", "example_kr": "", "example_uz": ""},
    {"kr": "기숙사", "roman": "gisuksa", "uz": "yotoqxona", "tts": "기숙사", "example_kr": "", "example_uz": ""},
    {"kr": "사진", "roman": "sajin", "uz": "rasm", "tts": "사진", "example_kr": "", "example_uz": ""},
    {"kr": "매일", "roman": "maeil", "uz": "har kuni", "tts": "매일", "example_kr": "", "example_uz": ""},
    {"kr": "그", "roman": "geu", "uz": "u (erkak)", "tts": "그", "example_kr": "", "example_uz": ""},
    {"kr": "반", "roman": "ban", "uz": "sinf", "tts": "반", "example_kr": "", "example_uz": ""},
    {"kr": "사랑하다", "roman": "saranghada", "uz": "sevmoq", "tts": "사랑하다", "example_kr": "", "example_uz": ""},
    {"kr": "서점", "roman": "seojeom", "uz": "kitob do‘koni", "tts": "서점", "example_kr": "", "example_uz": ""},
    {"kr": "빵집", "roman": "ppangjip", "uz": "nonvoyxona", "tts": "빵집", "example_kr": "", "example_uz": ""},
    {"kr": "화장실", "roman": "hwajangsil", "uz": "hojatxona", "tts": "화장실", "example_kr": "", "example_uz": ""},
    {"kr": "음식", "roman": "eumsik", "uz": "ovqat / taom", "tts": "음식", "example_kr": "", "example_uz": ""},
    {"kr": "가념품", "roman": "ganyeompum", "uz": "suvenir", "tts": "가념품", "example_kr": "", "example_uz": ""},
    {"kr": "그림", "roman": "geurim", "uz": "rasm", "tts": "그림", "example_kr": "", "example_uz": ""},
    {"kr": "학생", "roman": "haksaeng", "uz": "talaba", "tts": "학생", "example_kr": "", "example_uz": ""},
    {"kr": "친구", "roman": "chingu", "uz": "do‘st", "tts": "친구", "example_kr": "", "example_uz": ""},
    {"kr": "전화", "roman": "jeonhwa", "uz": "telefon", "tts": "전화", "example_kr": "", "example_uz": ""},
    {"kr": "자동차", "roman": "jadongcha", "uz": "mashina", "tts": "자동차", "example_kr": "", "example_uz": ""},
    {"kr": "개", "roman": "gae", "uz": "it", "tts": "개", "example_kr": "", "example_uz": ""}
]
