WORDS = [
    {"kr": "숫자", "roman": "sutja", "uz": "raqam / son", "tts": "숫자", "example_kr": "", "example_uz": ""},
    {"kr": "월요일", "roman": "wolyoil", "uz": "dushanba", "tts": "월요일", "example_kr": "", "example_uz": ""},
    {"kr": "화요일", "roman": "hwayoil", "uz": "seshanba", "tts": "화요일", "example_kr": "", "example_uz": ""},
    {"kr": "수요일", "roman": "suyoil", "uz": "chorshanba", "tts": "수요일", "example_kr": "", "example_uz": ""},
    {"kr": "목요일", "roman": "mogyoil", "uz": "payshanba", "tts": "목요일", "example_kr": "", "example_uz": ""},
    {"kr": "금요일", "roman": "geumyoil", "uz": "juma", "tts": "금요일", "example_kr": "", "example_uz": ""},
    {"kr": "토요일", "roman": "toyoil", "uz": "shanba", "tts": "토요일", "example_kr": "", "example_uz": ""},
    {"kr": "일요일", "roman": "iryoil", "uz": "yakshanba", "tts": "일요일", "example_kr": "", "example_uz": ""},
    {"kr": "주말", "roman": "jumal", "uz": "hafta oxiri", "tts": "주말", "example_kr": "", "example_uz": ""},
    {"kr": "날짜", "roman": "naljja", "uz": "sana", "tts": "날짜", "example_kr": "", "example_uz": ""},
    {"kr": "요일", "roman": "yoil", "uz": "hafta kuni", "tts": "요일", "example_kr": "", "example_uz": ""},
    {"kr": "며칠", "roman": "myeochil", "uz": "qaysi kun / necha kun", "tts": "며칠", "example_kr": "", "example_uz": ""},
    {"kr": "시험", "roman": "siheom", "uz": "imtixon", "tts": "시험", "example_kr": "", "example_uz": ""},
    {"kr": "언제", "roman": "eonje", "uz": "qachon", "tts": "언제", "example_kr": "", "example_uz": ""},
    {"kr": "무슨", "roman": "museun", "uz": "qaysi", "tts": "무슨", "example_kr": "", "example_uz": ""},
    {"kr": "생일", "roman": "saeng-il", "uz": "tug‘ilgan kun", "tts": "생일", "example_kr": "", "example_uz": ""},
    {"kr": "하고", "roman": "hago", "uz": "bilan", "tts": "하고", "example_kr": "", "example_uz": ""},
    {"kr": "크리스마스", "roman": "keuriseumaseu", "uz": "krismas", "tts": "크리스마스", "example_kr": "", "example_uz": ""},
    {"kr": "파티", "roman": "pati", "uz": "bazm / party", "tts": "파티", "example_kr": "", "example_uz": ""},
    {"kr": "시간", "roman": "sigan", "uz": "vaqt", "tts": "시간", "example_kr": "", "example_uz": ""},
    {"kr": "미안하다", "roman": "mianhada", "uz": "uzr so‘ramoq", "tts": "미안하다", "example_kr": "", "example_uz": ""},
    {"kr": "약속", "roman": "yaksok", "uz": "uchrashuv / vada", "tts": "약속", "example_kr": "", "example_uz": ""},
    {"kr": "같이", "roman": "gachi", "uz": "birga", "tts": "같이", "example_kr": "", "example_uz": ""},
    {"kr": "어제", "roman": "eoje", "uz": "kecha", "tts": "어제", "example_kr": "", "example_uz": ""},
    {"kr": "코엑스몰", "roman": "koegseumol", "uz": "Coex mall", "tts": "코엑스몰", "example_kr": "", "example_uz": ""},
    {"kr": "카드", "roman": "kadeu", "uz": "karta", "tts": "카드", "example_kr": "", "example_uz": ""},
    {"kr": "선물", "roman": "seonmul", "uz": "sovg‘a", "tts": "선물", "example_kr": "", "example_uz": ""},
    {"kr": "세수하다", "roman": "sesuhada", "uz": "yuvinmoq", "tts": "세수하다", "example_kr": "", "example_uz": ""},
    {"kr": "이를 닦다", "roman": "ireul takda", "uz": "tish yuvmoq", "tts": "이를 닦다", "example_kr": "", "example_uz": ""},
    {"kr": "거기", "roman": "geogi", "uz": "o‘sha joy / u yer", "tts": "거기", "example_kr": "", "example_uz": ""},
    {"kr": "산책하다", "roman": "sanchaekada", "uz": "sayr qilmoq", "tts": "산책하다", "example_kr": "", "example_uz": ""},
    {"kr": "사진을 찍다", "roman": "sajineul jjikda", "uz": "rasmga tushirmoq", "tts": "사진을 찍다", "example_kr": "", "example_uz": ""},
    {"kr": "누구", "roman": "nugu", "uz": "kim", "tts": "누구", "example_kr": "", "example_uz": ""},
    {"kr": "혼자", "roman": "honja", "uz": "yolg‘iz", "tts": "혼자", "example_kr": "", "example_uz": ""},
    {"kr": "끝나다", "roman": "kkeutnada", "uz": "tugamoq / yakunlanmoq", "tts": "끝나다", "example_kr": "", "example_uz": ""},
    {"kr": "강남역", "roman": "gangnam-yeok", "uz": "Gangnam bekati", "tts": "강남역", "example_kr": "", "example_uz": ""},
    {"kr": "그래서", "roman": "geuraeseo", "uz": "shuning uchun", "tts": "그래서", "example_kr": "", "example_uz": ""},
    {"kr": "내일", "roman": "nae-il", "uz": "ertaga", "tts": "내일", "example_kr": "", "example_uz": ""},
    {"kr": "스케줄", "roman": "seukejul", "uz": "reja / kun tartibi", "tts": "스케줄", "example_kr": "", "example_uz": ""},
    {"kr": "지난주", "roman": "jinanju", "uz": "o‘tgan hafta", "tts": "지난주", "example_kr": "", "example_uz": ""},
    {"kr": "양력", "roman": "yangnyeok", "uz": "quyosh kalendari", "tts": "양력", "example_kr": "", "example_uz": ""},
    {"kr": "음력", "roman": "eumnyeok", "uz": "oy kalendari", "tts": "음력", "example_kr": "", "example_uz": ""},
    {"kr": "설날", "roman": "seollal", "uz": "koreys yangi yili (Sulnal)", "tts": "설날", "example_kr": "", "example_uz": ""},
    {"kr": "세배를 하다", "roman": "sebaereul hada", "uz": "tazim qilmoq (yangi yil marosimi)", "tts": "세배를 하다", "example_kr": "", "example_uz": ""},
    {"kr": "떡국", "roman": "tteokguk", "uz": "tokkuk sho‘rva", "tts": "떡국", "example_kr": "", "example_uz": ""},
    {"kr": "추석", "roman": "chuseok", "uz": "hosil bayrami / shukronalik kuni", "tts": "추석", "example_kr": "", "example_uz": ""},
    {"kr": "차례를 지내다", "roman": "charyereul jinaeda", "uz": "marosim o‘tkazmoq", "tts": "차례를 지내다", "example_kr": "", "example_uz": ""},
    {"kr": "송편", "roman": "songpyeon", "uz": "guruchli pishiriq", "tts": "송편", "example_kr": "", "example_uz": ""},
    {"kr": "가족", "roman": "gajok", "uz": "oila", "tts": "가족", "example_kr": "", "example_uz": ""},
    {"kr": "집", "roman": "jip", "uz": "uy", "tts": "집", "example_kr": "", "example_uz": ""},
    {"kr": "기분", "roman": "gibun", "uz": "kayfiyat", "tts": "기분", "example_kr": "", "example_uz": ""}
]
