WORDS = [
    # 6과 — 1-bo‘lim
    {"kr": "샌드위치", "roman": "saendeuichi", "uz": "sendvich", "tts": "샌드위치", "example_kr": "", "example_uz": ""},
    {"kr": "스파게티", "roman": "seupageti", "uz": "spagetti", "tts": "스파게티", "example_kr": "", "example_uz": ""},
    {"kr": "피자", "roman": "pija", "uz": "pitsa", "tts": "피자", "example_kr": "", "example_uz": ""},
    {"kr": "햄버거", "roman": "haembeogeo", "uz": "gamburger", "tts": "햄버거", "example_kr": "", "example_uz": ""},
    {"kr": "귤", "roman": "gyul", "uz": "mandarin", "tts": "귤", "example_kr": "", "example_uz": ""},
    {"kr": "딸기", "roman": "ttalgi", "uz": "qulupnay", "tts": "딸기", "example_kr": "", "example_uz": ""},
    {"kr": "사과", "roman": "sagwa", "uz": "olma", "tts": "사과", "example_kr": "", "example_uz": ""},
    {"kr": "수박", "roman": "subak", "uz": "tarvuz", "tts": "수박", "example_kr": "", "example_uz": ""},
    {"kr": "앉다", "roman": "anjda", "uz": "o‘tirmoq", "tts": "앉다", "example_kr": "", "example_uz": ""},
    {"kr": "주다", "roman": "juda", "uz": "bermoq", "tts": "주다", "example_kr": "", "example_uz": ""},
    {"kr": "잠깐만", "roman": "jamkkanman", "uz": "biroz / bir daqiqa", "tts": "잠깐만", "example_kr": "", "example_uz": ""},
    {"kr": "기다리다", "roman": "gidalida", "uz": "kutmoq", "tts": "기다리다", "example_kr": "", "example_uz": ""},
    {"kr": "빵", "roman": "ppang", "uz": "non", "tts": "빵", "example_kr": "", "example_uz": ""},
    {"kr": "몇", "roman": "myeot", "uz": "necha / qancha", "tts": "몇", "example_kr": "", "example_uz": ""},
    {"kr": "아이스크림", "roman": "aiseukeulim", "uz": "muzqaymoq", "tts": "아이스크림", "example_kr": "", "example_uz": ""},
    {"kr": "주스", "roman": "juseu", "uz": "sharbat", "tts": "주스", "example_kr": "", "example_uz": ""},
    {"kr": "녹차", "roman": "nokcha", "uz": "ko‘k choy", "tts": "녹차", "example_kr": "", "example_uz": ""},
    {"kr": "콜라", "roman": "kolla", "uz": "kola", "tts": "콜라", "example_kr": "", "example_uz": ""},
    {"kr": "메뉴", "roman": "menyu", "uz": "menyu", "tts": "메뉴", "example_kr": "", "example_uz": ""},
    {"kr": "좋아하다", "roman": "joahada", "uz": "yaxshi ko‘rmoq", "tts": "좋아하다", "example_kr": "", "example_uz": ""},
    {"kr": "우동", "roman": "udong", "uz": "udon taomi", "tts": "우동", "example_kr": "", "example_uz": ""},
    {"kr": "맥주", "roman": "maekju", "uz": "pivo", "tts": "맥주", "example_kr": "", "example_uz": ""},
    {"kr": "물건", "roman": "mulgeon", "uz": "narsa", "tts": "물건", "example_kr": "", "example_uz": ""},
    {"kr": "개수", "roman": "gaesu", "uz": "sanoq / soni", "tts": "개수", "example_kr": "", "example_uz": ""},
    {"kr": "그래요", "roman": "geuraeyo", "uz": "shunday", "tts": "그래요", "example_kr": "", "example_uz": ""},
    {"kr": "여기요", "roman": "yeogiyo", "uz": "kechirasiz (chaqirish)", "tts": "여기요", "example_kr": "", "example_uz": ""},
    {"kr": "맛있다", "roman": "masitda", "uz": "mazali", "tts": "맛있다", "example_kr": "", "example_uz": ""},

    # 6과 — 2-bo‘lim
    {"kr": "좋다", "roman": "jota", "uz": "yaxshi", "tts": "좋다", "example_kr": "", "example_uz": ""},
    {"kr": "싸다", "roman": "ssada", "uz": "arzon", "tts": "싸다", "example_kr": "", "example_uz": ""},
    {"kr": "길", "roman": "gil", "uz": "yo‘l", "tts": "길", "example_kr": "", "example_uz": ""},
    {"kr": "복잡하다", "roman": "bokjaphada", "uz": "tiqilinch", "tts": "복잡하다", "example_kr": "", "example_uz": ""},
    {"kr": "노래", "roman": "norae", "uz": "qo‘shiq", "tts": "노래", "example_kr": "", "example_uz": ""},
    {"kr": "아리랑", "roman": "arirang", "uz": "koreys xalq qo‘shig‘i", "tts": "아리랑", "example_kr": "", "example_uz": ""},
    {"kr": "바지", "roman": "baji", "uz": "shim", "tts": "바지", "example_kr": "", "example_uz": ""},
    {"kr": "운동화", "roman": "undonghwa", "uz": "krossovka", "tts": "운동화", "example_kr": "", "example_uz": ""},
    {"kr": "아저씨", "roman": "ajeossi", "uz": "amaki", "tts": "아저씨", "example_kr": "", "example_uz": ""},
    {"kr": "모두", "roman": "modu", "uz": "hammasi", "tts": "모두", "example_kr": "", "example_uz": ""},
    {"kr": "또", "roman": "tto", "uz": "yana", "tts": "또", "example_kr": "", "example_uz": ""},
    {"kr": "키위", "roman": "kiwi", "uz": "kivi", "tts": "키위", "example_kr": "", "example_uz": ""},
    {"kr": "파인애플", "roman": "painaepeul", "uz": "ananas", "tts": "파인애플", "example_kr": "", "example_uz": ""},
    {"kr": "박스", "roman": "bakseu", "uz": "quti", "tts": "박스", "example_kr": "", "example_uz": ""},
    {"kr": "멜론", "roman": "mellon", "uz": "qovun", "tts": "멜론", "example_kr": "", "example_uz": ""},
    {"kr": "과자", "roman": "gwaja", "uz": "pishiriq", "tts": "과자", "example_kr": "", "example_uz": ""},
    {"kr": "달걀", "roman": "dalgyal", "uz": "tuxum", "tts": "달걀", "example_kr": "", "example_uz": ""},
    {"kr": "휴지", "roman": "hyuji", "uz": "salfetka", "tts": "휴지", "example_kr": "", "example_uz": ""},
    {"kr": "케이크", "roman": "keikeu", "uz": "tort", "tts": "케이크", "example_kr": "", "example_uz": ""},
    {"kr": "아이스커피", "roman": "aiseukeopi", "uz": "muzli kofe", "tts": "아이스커피", "example_kr": "", "example_uz": ""},
    {"kr": "에스프레소", "roman": "eseupeureso", "uz": "espresso", "tts": "에스프레소", "example_kr": "", "example_uz": ""},
    {"kr": "돈가스", "roman": "dongaseu", "uz": "donkatsu (kotlet)", "tts": "돈가스", "example_kr": "", "example_uz": ""},
    {"kr": "점심", "roman": "jeomsim", "uz": "tushlik", "tts": "점심", "example_kr": "", "example_uz": ""},
    {"kr": "급", "roman": "geup", "uz": "daraja", "tts": "급", "example_kr": "", "example_uz": ""},
    {"kr": "물건", "roman": "mulgeon", "uz": "narsa", "tts": "물건", "example_kr": "", "example_uz": ""},
    {"kr": "팔다", "roman": "palda", "uz": "sotmoq", "tts": "팔다", "example_kr": "", "example_uz": ""},
    {"kr": "인지", "roman": "inji", "uz": "inch (o‘lchov)", "tts": "인지", "example_kr": "", "example_uz": ""},

    # Sonlar
    {"kr": "하나", "roman": "hana", "uz": "bir", "tts": "하나", "example_kr": "", "example_uz": ""},
    {"kr": "둘", "roman": "dul", "uz": "ikki", "tts": "둘", "example_kr": "", "example_uz": ""},
    {"kr": "셋", "roman": "set", "uz": "uch", "tts": "셋", "example_kr": "", "example_uz": ""},
    {"kr": "넷", "roman": "net", "uz": "to‘rt", "tts": "넷", "example_kr": "", "example_uz": ""},
    {"kr": "다섯", "roman": "daseot", "uz": "besh", "tts": "다섯", "example_kr": "", "example_uz": ""},
    {"kr": "여섯", "roman": "yeoseot", "uz": "olti", "tts": "여섯", "example_kr": "", "example_uz": ""},
    {"kr": "일곱", "roman": "ilgop", "uz": "yetti", "tts": "일곱", "example_kr": "", "example_uz": ""},
    {"kr": "여덟", "roman": "yeodeol", "uz": "sakkiz", "tts": "여덟", "example_kr": "", "example_uz": ""},
    {"kr": "아홉", "roman": "ahop", "uz": "to‘qqiz", "tts": "아홉", "example_kr": "", "example_uz": ""},
    {"kr": "열", "roman": "yeol", "uz": "o‘n", "tts": "열", "example_kr": "", "example_uz": ""},

    # 6과 — 3-bo‘lim
    {"kr": "아주", "roman": "aju", "uz": "juda", "tts": "아주", "example_kr": "", "example_uz": ""},
    {"kr": "리모컨", "roman": "rimokeon", "uz": "pult", "tts": "리모컨", "example_kr": "", "example_uz": ""},
    {"kr": "깨끗하다", "roman": "kkaekkeutada", "uz": "toza", "tts": "깨끗하다", "example_kr": "", "example_uz": ""},
    {"kr": "많다", "roman": "manta", "uz": "ko‘p", "tts": "많다", "example_kr": "", "example_uz": ""},
    {"kr": "권", "roman": "gwon", "uz": "-ta (kitoblar uchun sanoq)", "tts": "권", "example_kr": "", "example_uz": ""},
    {"kr": "전화하다", "roman": "jeonhwahada", "uz": "telefon qilmoq", "tts": "전화하다", "example_kr": "", "example_uz": ""},
    {"kr": "비싸다", "roman": "bissada", "uz": "qimmat", "tts": "비싸다", "example_kr": "", "example_uz": ""},
    {"kr": "깎아 주다", "roman": "kkakka juda", "uz": "arzon qilib bermoq", "tts": "깎아 주다", "example_kr": "", "example_uz": ""},
    {"kr": "백김치", "roman": "baek gimchi", "uz": "oq kimchi", "tts": "백김치", "example_kr": "", "example_uz": ""},
    {"kr": "깍두기", "roman": "kkakdugi", "uz": "rediski kimchi", "tts": "깍두기", "example_kr": "", "example_uz": ""},
    {"kr": "오이김치", "roman": "oi gimchi", "uz": "bodring kimchi", "tts": "오이김치", "example_kr": "", "example_uz": ""},
    {"kr": "물김치", "roman": "mul gimchi", "uz": "suvli kimchi", "tts": "물김치", "example_kr": "", "example_uz": ""},
    {"kr": "이런", "roman": "ireon", "uz": "bunday", "tts": "이런", "example_kr": "", "example_uz": ""},
    {"kr": "김치볶음밥", "roman": "gimchi bokkeumbap", "uz": "kimchi bilan qovurilgan guruch", "tts": "김치볶음밥", "example_kr": "", "example_uz": ""},
    {"kr": "김치전", "roman": "gimchijeon", "uz": "kimchi quymoq", "tts": "김치전", "example_kr": "", "example_uz": ""},
    {"kr": "얼마", "roman": "eolma", "uz": "qancha", "tts": "얼마", "example_kr": "", "example_uz": ""},
    {"kr": "십 원", "roman": "sip won", "uz": "10 von", "tts": "십 원", "example_kr": "", "example_uz": ""},
    {"kr": "오십 원", "roman": "osip won", "uz": "50 von", "tts": "오십 원", "example_kr": "", "example_uz": ""},
    {"kr": "백 원", "roman": "baeg won", "uz": "100 von", "tts": "백 원", "example_kr": "", "example_uz": ""},
    {"kr": "오백 원", "roman": "obaeg won", "uz": "500 von", "tts": "오백 원", "example_kr": "", "example_uz": ""},
    {"kr": "천 원", "roman": "cheon won", "uz": "1000 von", "tts": "천 원", "example_kr": "", "example_uz": ""},
    {"kr": "오천 원", "roman": "ocheon won", "uz": "5000 von", "tts": "오천 원", "example_kr": "", "example_uz": ""},
    {"kr": "만 원", "roman": "man won", "uz": "10.000 von", "tts": "만 원", "example_kr": "", "example_uz": ""},
    {"kr": "오만 원", "roman": "oman won", "uz": "50.000 von", "tts": "오만 원", "example_kr": "", "example_uz": ""},
    {"kr": "물건", "roman": "mulgeon", "uz": "narsa", "tts": "물건", "example_kr": "", "example_uz": ""},
    {"kr": "끝", "roman": "kkeut", "uz": "yakun / tugadi", "tts": "끝", "example_kr": "", "example_uz": ""}
]
